### ISSUE TITLE
When orientation changes iOS reports previous orientation instead of current orientation

### ISSUE THREAD

**Issue by wm17** [rmtmckenzie/flutter_native_device_orientation#13]
I believe this is because OrientationListener uses statusBarOrientation, but adds an observer for UIDeviceOrientationDidChangeNotification instead of UIApplicationDidChangeStatusBarOrientationNotification.

It looks like on iOS device orientation changes before the status bar orientation, so when getDeviceOrientation gets the statusBarOrientation it hasn't changed yet and retrieves the previous orientation.

**Comment by PerLycke** [comment]
@rmtmckenzie We've had an app in production for a year, and your plugin rocks. This fix is needed though, but not for new and snappy devices but for older iPads. For exempel, registering the correct orientation works on all our devices except our iPad Air from 2013, where without this commit it registers the previous orientation. Using this fix didn't cause any issues on other devices looking at the last year's use, it just fixes the issue on older iPads.

Hope this information can be to some help, cheers

**Comment by rmtmckenzie** [comment]
Testing, will integrate in 1.1.2. Sorry for the _extremely_ long wait on this one!
