### ISSUE TITLE
Error: Getter not found: 'detached'.

### ISSUE THREAD

**Issue by Al4han** [rmtmckenzie/flutter_native_device_orientation#14]
When using your plugin following error is thrown at compile time:
`native_device_orientation-0.3.0/lib/native_device_orientation.dart:149:30: Error: Getter not found: 'detached'.
      case AppLifecycleState.detached:`
It would be really nice, if you could look into that :slightly_smiling_face:

**Comment by Al4han** [comment]
Btw.: i am on `Flutter 1.9.1+hotfix.6 • channel stable`

**Comment by rmtmckenzie** [comment]
oh shoot I messed up the constraints for flutter versions. You just need to downgrade to 0.2.0 of this plugin as it still uses "suspending" instead of detached which will be coming through once the next version of flutter hits the stable channel.
