### ISSUE TITLE
Getter not found: 'detached'

### ISSUE THREAD

**Issue by fatimahossny** [rmtmckenzie/flutter_native_device_orientation#16]
when I run the project complier throw this error . any help is appreciated 
native_device_orientation.dart:149:30: Error: Getter not found: 'detached'.
      case AppLifecycleState.detached:

**Comment by rmtmckenzie** [comment]
See #14. Just downgrade to the last version, the current version is for the most recent version of flutter which changes 'detached' to 'suspending'.
