### ISSUE TITLE
Response landscapeRight when the device is landscapeLeft

### ISSUE THREAD

**Issue by edeortuzar** [rmtmckenzie/flutter_native_device_orientation#18]
When I have a device on landscape left and I run the NativeDeviceOrientationReader twice, beacause I have two pages where I evaluate the orientation, the second page recive landscapeRight from the plugin  always.

When I debugin the plugin I saw that the second time the If statment on 161 line response true, and get the orientation from OrientationBuilder and recive Orientation.landscape soo the plugin response NativeDeviceOrientation.landscapeRight.

**Comment by edeortuzar** [comment]
When I have the problem, I rotate to landscapeRight and after rotate again to landscapeLeft, I recived landscapeLeft from plugin response.

**Comment by nicolaslucer0** [comment]
Just to add some info, the problem appears when you are in page `A` which has a `NativeDeviceOrientationReader` and goes to page `B` which has another `NativeDeviceOrientationReader`.

Then, the page which is supposed to has a `NativeDeviceOrientation.landscapeLeft` will have `NativeDeviceOrientation.landscapeRight` even if I don't change the orientation.

> Note: If I rotate the phone, It begins to work properly.

*I'm using this code:*
```dart
NativeDeviceOrientationReader(
    builder: (context) {
    NativeDeviceOrientation orientation = NativeDeviceOrientationReader.orientation(context);
    var quarterTurns = 0;
    if (orientation == NativeDeviceOrientation.landscapeLeft) {
          quarterTurns = 3;
     } else if (orientation == NativeDeviceOrientation.landscapeRight) {
          quarterTurns = 1;
     }
  }
),
```

I don't know if somehow I have to close the reader or something.

Thanks in advance !

**Comment by zanesc** [comment]
I have this exact issue. Anyone figured out a workaround?

**Comment by zanesc** [comment]
Thanks @edeortuzar for doing the debugging. I was able to fix the issue. Checkout my pull request.
