### ISSUE TITLE
Null safety

### ISSUE THREAD

**Issue by zs-dima** [rmtmckenzie/flutter_native_device_orientation#28]
Could be nice to create null safety version

**Comment by rmtmckenzie** [comment]
I agree. I'll see if I can find time to do it this weekend. In the meantime PRs are always welcome =)

**Comment by gabrielginter** [comment]
+1

Flutter 2.0 was released hours ago, would be great to have this in the near future to migrate our apps

Thanks

**Comment by rmtmckenzie** [comment]
Whoops this was completed a long time ago but I never closed the issue.
