### ISSUE TITLE
Plugin returns oposite orientation when in landscape on iOS

### ISSUE THREAD

**Issue by nazdream** [rmtmckenzie/flutter_native_device_orientation#33]
I am trying to lock device orientation on one of the screens in a flutter app. The problem I am facing is that the plugin returning opposite orientation on iOS when the app in landscape mode, I can manually change it in the app, but I think you should be aware of this issue.

The device used: iPhone xs with iOS 15.0

flutter --version output:
Flutter 2.5.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 18116933e7 (5 weeks ago) • 2021-10-15 10:46:35 -0700
Engine • revision d3ea636dc5
Tools • Dart 2.14.4

native_device_orientation: 1.0.0

**Comment by rmtmckenzie** [comment]
I've tested this with iOS 15.2.1 and am not seeing this issue (although I don't have an XS to test on). I'm going to close for now but if more people see the same issue let me know.
