### ISSUE TITLE
Property to control the sensibility of the sensors

### ISSUE THREAD

**Issue by fabianbrandscheid** [rmtmckenzie/flutter_native_device_orientation#35]
Hi,

when using the NativeOrientationBuilder with useSensor = true, the system already reacts to very fine
movements. Minimal movements quickly change the orientation, which can lead to a choppy UI (see video in the appendix --> look at the icons in the appbar and the preview image at the bottom):

https://user-images.githubusercontent.com/38261693/148977674-78eb5e0e-08e1-4cf7-b001-17d6855bd5a9.mov

Would it be possible to add another property here to control how fine the sensors react?

**Comment by rmtmckenzie** [comment]
I don't think a full-on property is needed at this point, I've just made it so that when the device is close to flat any changes are ignored. If that doesn't do it for you I'd encourage you to submit a pr - the relevant iOS code is in ios/Classes/SensorListener.m
