### ISSUE TITLE
Landscape left not working as expected

### ISSUE THREAD

**Issue by ervindobri** [rmtmckenzie/flutter_native_device_orientation#36]
I'm trying to build an app which is landscape only oriented, and a weird issue appeared.
When in LandscapeLeft the orientation built is sometimes LandscapeLeft, sometimes PortraitUp;
Device: iPhone 12 mini.

Sample code:
```
return NativeDeviceOrientationReader(
        useSensor: true,
        builder: (context) {
          final orientation =
              NativeDeviceOrientationReader.orientation(context);
          print(orientation);
          return SomeWidget();
});
```

Output:
flutter: NativeDeviceOrientation.landscapeLeft
flutter: NativeDeviceOrientation.portraitUp

**Comment by rmtmckenzie** [comment]
This is because when the device returns an unknown orientation, it defaults to portrait up. You can now change this by setting "defaultOrientation" to "NativeDeviceOrientation.landscapeLeft"
