### ISSUE TITLE
Return error when call using useSensor:true on iOS simulator

### ISSUE THREAD

**Issue by johnspackman** [rmtmckenzie/flutter_native_device_orientation#47]
I can't get `useSensor:true` to ever work on the simulator - the `NativeDeviceOrientationCommunicator. orientation` never returns from it's promise and the `onOrientationChanged` stream never fires any events

Is this a known issue?

**Comment by desmeit** [comment]
Can the plugin author confirm this? useSensor is not working with simulator?

**Comment by rmtmckenzie** [comment]
yes, we do a check for `isDeviceMotionAvailable` which would return false on simulators and then the sensor data would never be read. Should probably return some sort of error though.

**Comment by rmtmckenzie** [comment]
I believe it should return an error on the simulator now rather than simply never returning.
