### ISSUE TITLE
Orientation is different on iOS than on Android

### ISSUE THREAD

**Issue by nachtmaar** [rmtmckenzie/flutter_native_device_orientation#5]
Hi,

I am using your plugin to fix an [orientation issue](https://github.com/flutter/flutter/issues/16587#issuecomment-430151728) with the flutter camera plugin.

I am experiencing different orientations depending on the platform.

If you use the following code both on a iOS device and an Android device, you will see different orientations being reported.

Rotate the Android phone by 90° to the right (home button on left side), then you get `NativeDeviceOrientation.landscapeRight`.
If rotating the iOS phone by 90° to the right (home button on left side), then you get `NativeDeviceOrientation.landscapeLeft`.

If you read the Apple docs on [UIDeviceOrientation.landscapeLeft](https://developer.apple.com/documentation/uikit/uideviceorientation/landscapeleft), it states the following 

> The device is in landscape mode, with the device held upright and the home button on the **right** side.

`NativeDeviceOrientation.portraitDown` isn't reported at all for iOS device (also not on simulator).

I am using plugin version `0.0.3`.

```dart
import 'package:flutter/material.dart';
import 'package:native_device_orientation/native_device_orientation.dart';

main() {
  runApp(App());
}

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        home: Scaffold(
      appBar: AppBar(
        title: Text('Rotation'),
      ),
      body: buildOrientationReader(),
    ));
  }

  Widget buildOrientationReader() {
    var rotatedBody = NativeDeviceOrientationReader(builder: (context) {
      NativeDeviceOrientation orientation =
          NativeDeviceOrientationReader.orientation(context);
      print(orientation.toString());

      int turns;
      switch (orientation) {
        case NativeDeviceOrientation.landscapeRight:
          turns = 1;
          break;
        case NativeDeviceOrientation.portraitDown:
          turns = 2;
          break;
        case NativeDeviceOrientation.landscapeLeft:
          turns = 3;
          break;
        default:
          turns = 0;
          break;
      }

      print('turns: $turns');

      return RotatedBox(
        child: Image.network(
            'https://cdn-images-1.medium.com/max/1200/1*5-aoK8IBmXve5whBQM90GA.png'),
        quarterTurns: turns,
      );
    });
    return rotatedBody;
  }
}
```

**Comment by desmese** [comment]
Hi, I had the same issue as well. 

The iOS version uses the statusbarOrientation to determine the orientation of the device. The statusbarOrientation is of the class [UIInterfaceOrientation](https://developer.apple.com/documentation/uikit/uiinterfaceorientation) 

According to the documentation the landscape orientation is reversed to the actual device orientation.
> Notice that UIDeviceOrientationLandscapeRight is assigned to UIInterfaceOrientationLandscapeLeft and UIDeviceOrientationLandscapeLeft is assigned to UIInterfaceOrientationLandscapeRight; the reason for this is that rotating the device requires rotating the content in the opposite direction.

The reason it isn't showing portraitDown is because the demo is set to only use the following device orientations: Portrait, LandscapeLeft, LandscapeRight. The demo app doesn't support upside-down. The statusbar can never be shown upside-down in the demo. That's why portraitDown is never called. 

The statusbarOrientation is deprecated since iOS 10 so I changed the code to use the UIDeviceOrientation instead. The code isn't tested thoroughly but it seemed to work for me. It returns the orientation of the device as long as autorotate isn't disabled, and you don't use the 'SystemChrome.setPreferredOrientations' in your flutter code. To retrieve the actual device-orientation at all times you would need to use the orientation sensor. 

I added an extra local variable in the iOS-code to prevent returning FaceDown and FaceUp values
`UIDeviceOrientation lastDeviceOrientation = UIDeviceOrientationUnknown;
`

```
- (NSString*)getOrientation {
    UIDeviceOrientation deviceOrientation = [[UIDevice currentDevice] orientation];
    
    // exta check to make sure we don't return the FaceDown and FaceUp orientations but instead return the last known deviceOrientation.
    if(deviceOrientation != UIDeviceOrientationFaceDown && deviceOrientation != UIDeviceOrientationFaceUp) {
        lastDeviceOrientation = deviceOrientation;
    }

    switch (lastDeviceOrientation) {
            case UIDeviceOrientationPortrait:
            return PORTRAIT_UP;
            break;
            case UIDeviceOrientationPortraitUpsideDown:
            return PORTRAIT_DOWN;
            break;
            case UIDeviceOrientationLandscapeLeft:
            return LANDSCAPE_LEFT;
            break;
            case UIDeviceOrientationLandscapeRight:
            return LANDSCAPE_RIGHT;
            break;
            case UIDeviceOrientationUnknown:
        default:
            return UNKNOWN;
            break;
    }
}
```

**Comment by rmtmckenzie** [comment]
Hi @desmese, and thanks for the PR!  I'll take a look at it when I get a chance - hopefully either later this week or the weekend.

**Comment by rmtmckenzie** [comment]
@desmese I've just been testing this more thoroughly and came across some issues. I've updated the plugin now with that fixed - it was always using useSensor regardless of the value passed in.  I also wanted to let you know that I've actually reverted back to using StatusBarOrientation for detecting the orientation, as the device orientation isn't what I actually intended the plugin to read. What I really want (when useSensor = false) is for the the plugin to report whatever the window (i.e. statusbar)'s orientation is. I have fixed it to return the correct values though (switch landscape left & right). 

And just an FYI - setting the status bar orientation is deprecated, but reading it isn't actually in the code (even though it does say it is in the documentation, but I always trust the code more than the documentation =D).

**Comment by desmese** [comment]
@rmtmckenzie Thanks for letting me know. Sorry about the bug. I am only using this plug-in with useSensor set to true to correct the orientation of the camera plug-in. The change in behavior doesn't affect me personally. I just came across this issue and realized it would be issue to fix. 

I just relied on the documentation regarding the statusBarOrientation being deprecated, but as long as the code doesn't says it is, you can still use it :)
