### ISSUE TITLE
[IOS] The Info.plist key 'BGTaskSchedulerPermittedIdentifiers' must contain a list of identifiers used to submit and handle tasks when 'UIBackgroundModes' has a value of 'processing'.

### ISSUE THREAD

**Issue by jacky87218** [rmtmckenzie/flutter_native_device_orientation#60]
Generate .ipa file for ios.

Build Error：

`
Asset validation failed (90771)
Missing Info.plist value. The Info.plist key 'BGTaskSchedulerPermittedIdentifiers' must contain a list of identifiers used to submit and handle tasks when 'UIBackgroundModes' has a value of 'processing'. For more information, refer to the Information Property List Key Reference at https://developer.apple.com/library/ios/documentation/General/Reference/InfoPlistKeyReference/Introduction/Introduction.html.
`

I tried to solve it in the following way ：
[The Info.plist key 'BGTaskSchedulerPermittedIdentifiers' must contain a list of identifiers used to submit and handle tasks when 'UIBackgroundModes' has a value of 'processing'. #105](https://github.com/fluttercommunity/flutter_workmanager/issues/105)

I want to understand why this plugin needs to use BGTaskSchedulerPermittedIdentifiers. 

Thanks.

**Comment by rmtmckenzie** [comment]
Why do you think that this plugin is the cause of that? AFAIK this plugin doesn't use any special background modes unless it's implicitly using one for the sensor listening. The only thing I can think of is that something is getting messed up because it's in obj-c instead of swift, but that seems unlikely to be the cause.

If you do the same build steps with the example app are you seeing the same thing?

**Comment by jacky87218** [comment]
Finally, I confirmed that the problem had nothing to do with this plugin.

We misunderstood because this error occurred together with this error:
```
Asset validation failed (90474)
Invalid bundle. The “UIInterfaceOrientationPortrait” orientations were provided for the UISupportedInterfaceOrientations Info.plist key in the com.capital.csc2g bundle, but you need to include all of the “UIInterfaceOrientationPortrait,UIInterfaceOrientationPortraitUpsideDown,UIInterfaceOrientationLandscapeLeft,UIInterfaceOrientationLandscapeRight” orientations to support iPad multitasking. 
```

Thanks for your reply and thank you for making this plugin, it helped me a lot.
