### ISSUE TITLE
crash on ios version 2.0.2

### ISSUE THREAD

**Issue by rpelant** [rmtmckenzie/flutter_native_device_orientation#67]
Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Termination Reason: SIGNAL 6 Abort trap: 6
Terminating Process: Runner [5133]

Triggered by Thread:  0

Last Exception Backtrace:
0   CoreFoundation                	0x1d513140c __exceptionPreprocess + 160 (NSException.m:202)
1   libobjc.A.dylib               	0x1ce40dc28 objc_exception_throw + 56 (objc-exception.mm:356)
2   Foundation                    	0x1cf9149d4 -[NSAssertionHandler handleFailureInFunction:file:lineNumber:description:] + 168 (NSException.m:251)
3   Flutter                       	0x102f8e634 0x1029a8000 + 6186548
4   Flutter                       	0x102f8e190 0x1029a8000 + 6185360
5   Flutter                       	0x102f8f3c0 0x1029a8000 + 6190016
6   Flutter                       	0x102f89d04 0x1029a8000 + 6167812
7   native_device_orientation     	0x101f7dcb0 thunk for @escaping @callee_unowned @convention(block) (@unowned Swift.AnyObject?) -> () + 160 (<compiler-generated>:0)
8   native_device_orientation     	0x101f7dcb0 specialized NativeDeviceOrientationPlugin.handle(_:result:) + 892 (NativeDeviceOrientationPlugin.swift:35)
9   native_device_orientation     	0x101f7ccf8 specialized NativeDeviceOrientationPlugin.handle(_:result:) + 16 (<compiler-generated>:0)
10  native_device_orientation     	0x101f7ccf8 @objc NativeDeviceOrientationPlugin.handle(_:result:) + 84
11  Flutter                       	0x102f89a38 0x1029a8000 + 6167096
12  Flutter                       	0x1029ebc00 0x1029a8000 + 277504
13  libdispatch.dylib             	0x1dbed57a8 _dispatch_call_block_and_release + 24 (init.c:1518)
14  libdispatch.dylib             	0x1dbed6780 _dispatch_client_callout + 16 (object.m:560)
15  libdispatch.dylib             	0x1dbeb7e10 _dispatch_main_queue_drain + 888 (queue.c:7794)
16  libdispatch.dylib             	0x1dbeb7a88 _dispatch_main_queue_callback_4CF$VARIANT$armv81 + 36 (queue.c:7954)
17  CoreFoundation                	0x1d51b99ac __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12 (CFRunLoop.c:1780)
18  CoreFoundation                	0x1d519d648 __CFRunLoopRun + 2080 (CFRunLoop.c:3147)
19  CoreFoundation                	0x1d51a1d20 CFRunLoopRunSpecific + 584 (CFRunLoop.c:3418)
20  GraphicsServices              	0x20d26d998 GSEventRunModal + 160 (GSEvent.c:2196)
21  UIKitCore                     	0x1d743480c -[UIApplication _run] + 868 (UIApplication.m:3782)
22  UIKitCore                     	0x1d7434484 UIApplicationMain + 312 (UIApplication.m:5372)
23  Runner                        	0x10097c614 main + 64 (AppDelegate.swift:6)
24  dyld                          	0x1f2958344 start + 1860 (dyldMain.cpp:1165)

**Comment by rpelant** [comment]
It seems it was already fixed 4 days ago in #66 . When the fix is expected to be released?

**Comment by rmtmckenzie** [comment]
Whoops my bad, I incorporated the fix but somehow missed publishing the package. It's uploading right now!
